---
- include: debian/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "Debian"

- include: redhat/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "RedHat"

- include: config.yml
  tags: monit_config

- include: custom.yml
  tags: monit_custom

- include: monitors.yml
  tags: monit_monitors

- include: integrations.yml
  tags: monit_integrations

- name: allow log file read
  shell: chmod +r {{monit_log_destination}}