---
- when: not monit_install_from_source
  block:
    - include_tasks: debian/pkg.yml
      when: ansible_os_family == "Debian"

    - include_tasks: redhat/pkg.yml
      when: ansible_os_family == "RedHat"
  tags: [monit_pkg, monit_install]

- include_tasks: install-from-source.yml
  tags: [monit_src, monit_install]
  when: monit_install_from_source

- include_tasks: install-binary.yml
  tags: [monit_bin, monit_install]
  when: monit_install_bin

- include_tasks: config.yml
  tags: monit_config

- include_tasks: custom.yml
  tags: monit_custom

- include_tasks: monitors.yml
  tags: monit_monitors

- include_tasks: integrations.yml
  tags: monit_integrations
