---
- when: not monit_install_from_source
  block:
    - include: debian/pkg.yml
      when: ansible_os_family == "Debian"

    - include: redhat/pkg.yml
      when: ansible_os_family == "RedHat"
  tags: [monit_pkg, monit_install]

- include: install-from-source.yml
  tags: [monit_src, monit_install]
  when: monit_install_from_source

- include: install-binary.yml
  tags: [monit_bin, monit_install]
  when: monit_install_bin

- include: config.yml
  tags: monit_config

- include: custom.yml
  tags: monit_custom

- include: monitors.yml
  tags: monit_monitors

- include: integrations.yml
  tags: monit_integrations
