---
- include: debian/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "Debian"

- include: redhat/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "RedHat"

- include: install-from-source.yml
  tags: monit_src
  when: monit_reinstall_from_source

- include: config.yml
  tags: monit_config

- include: custom.yml
  tags: monit_custom

- include: monitors.yml
  tags: monit_monitors

- include: integrations.yml
  tags: monit_integrations
