---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:16.04
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-${USER}/tmp
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
    enabled: False
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge

    - side_effect
    - verify
    - destroy
